config/routes.rb
AsiPrivate::Application.routes.draw do
  resources :items

  resources :clients

  resources :invoices

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  root :to => "welcome#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :invoice, :dependent => :destroy
  
  validates :name, :presence => true
  validates :email, :format => { :with => /^(.+@.+\..+)?$/, :message => "is not a valid email address." }
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  STATUS_PI = 'Performa Invoice'
  STATUS_PO  = 'Purchase Order'
  STATUS_SO  = 'Sales Order'
  
  belongs_to :client
  has_many :items, :dependent => :destroy
  
  accepts_nested_attributes_for :items, :allow_destroy => true
  
  validates :code, :client_id, :presence => true
  validates :status, :inclusion => { :in => [STATUS_SO, STATUS_PO, STATUS_PI], :message => "You need to pick one status." }
  validates :tax, :discount, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
  
  class << self
    def suggest_code
      invoice = order('created_at desc').limit(1).first
      if invoice
        "SO 00#{invoice.id + 1}"
      else
        ""
      end
    end

    def status_collection
      {
        "Performa Invoice" => STATUS_PI,
        "Purchase Order" => STATUS_PO,
        "Sales Order" => STATUS_SO
      }
    end
    
    def this_month
      where('created_at >= ?', Date.new(Time.now.year, Time.now.month, 1).to_datetime)
    end
  end
  
  def items_total
    items_total = 0
    self.items.each do |i|
      items_total += i.total
    end
    items_total
  end
  
  def total
    items_total * (1 - self.discount / 100) * (1 + self.tax / 100)
  end
  
  def subtotal
    items_total * (1 - self.discount / 100)
  end
  
  def taxes
    subtotal * (self.tax / 100)
  end
  
  def status_tag
    case self.status
      when STATUS_PI then :error
      when STATUS_PO then :warning
      when STATUS_SO then :ok
    end
  end
  
  def invoice_location
    "#{Rails.root}/pdfs/invoice-#{self.code}.pdf"
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :invoice
  
  validates :quantity, :presence => true, :numericality => { :integer => true }
  validates :amount, :presence => true, :numericality => true
  validates :description, :presence => true
  
  def total
    self.quantity * self.amount
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < InheritedResources::Base
end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
 
 
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :tin %><br />
    <%= f.text_field :tin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Tin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.address %></td>
    <td><%= client.phone %></td>
    <td><%= client.email %></td>
    <td><%= client.tin %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Address:</b>
  <%= @client.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @client.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @client.email %>
</p>

<p>
  <b>Tin:</b>
  <%= @client.tin %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :terms %><br />
    <%= f.text_area :terms %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :tax %><br />
    <%= f.text_field :tax %>
  </div>
  <div class="field">
    <%= f.label :discount %><br />
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :sales_engineer %><br />
    <%= f.text_field :sales_engineer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Notes</th>
    <th>Terms</th>
    <th>Status</th>
    <th>Due date</th>
    <th>Tax</th>
    <th>Discount</th>
    <th>Client</th>
    <th>Sales engineer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invoices.each do |invoice| %>
  <tr>
    <td><%= invoice.code %></td>
    <td><%= invoice.notes %></td>
    <td><%= invoice.terms %></td>
    <td><%= invoice.status %></td>
    <td><%= invoice.due_date %></td>
    <td><%= invoice.tax %></td>
    <td><%= invoice.discount %></td>
    <td><%= invoice.client_id %></td>
    <td><%= invoice.sales_engineer %></td>
    <td><%= link_to 'Show', invoice %></td>
    <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
    <td><%= link_to 'Destroy', invoice, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @invoice.code %>
</p>

<p>
  <b>Notes:</b>
  <%= @invoice.notes %>
</p>

<p>
  <b>Terms:</b>
  <%= @invoice.terms %>
</p>

<p>
  <b>Status:</b>
  <%= @invoice.status %>
</p>

<p>
  <b>Due date:</b>
  <%= @invoice.due_date %>
</p>

<p>
  <b>Tax:</b>
  <%= @invoice.tax %>
</p>

<p>
  <b>Discount:</b>
  <%= @invoice.discount %>
</p>

<p>
  <b>Client:</b>
  <%= @invoice.client_id %>
</p>

<p>
  <b>Sales engineer:</b>
  <%= @invoice.sales_engineer %>
</p>


<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :invoice_id %><br />
    <%= f.text_field :invoice_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Quantity</th>
    <th>Amount</th>
    <th>Description</th>
    <th>Invoice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.quantity %></td>
    <td><%= item.amount %></td>
    <td><%= item.description %></td>
    <td><%= item.invoice_id %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quantity:</b>
  <%= @item.quantity %>
</p>

<p>
  <b>Amount:</b>
  <%= @item.amount %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Invoice:</b>
  <%= @item.invoice_id %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AsiPrivate</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>